#!/usr/bin/env python3
"""
Detect GPU hardware and generate docker-compose compute overrides.
Run before first `docker compose up` to auto-configure for best performance.

Detects: NVIDIA > AMD (ROCm) > Intel (XPU) > CPU fallback
"""
from __future__ import annotations

import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path


def run(cmd: list[str], check: bool = False) -> tuple[int, str]:
    """Run command, return (returncode, stdout+stderr)."""
    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=10,
        )
        out = (r.stdout or "") + (r.stderr or "")
        return r.returncode, out.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return -1, ""


def detect_nvidia() -> bool:
    """Check for NVIDIA GPU via nvidia-smi."""
    code, out = run(["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"])
    return code == 0 and bool(out)


def detect_amd() -> bool:
    """Check for AMD GPU (ROCm)."""
    if platform.system() != "Linux":
        return False
    # ROCm: rocm-smi or /dev/kfd
    if shutil.which("rocm-smi"):
        code, _ = run(["rocm-smi", "--showproductname"])
        return code == 0
    return Path("/dev/kfd").exists()


def detect_intel() -> bool:
    """Check for Intel GPU (XPU)."""
    if platform.system() != "Linux":
        return False
    # Intel oneAPI / level-zero
    return Path("/dev/dri").exists() and any(
        p.name.startswith("renderD") for p in Path("/dev/dri").iterdir()
    )


def detect() -> str:
    """Return: nvidia | amd | intel | cpu."""
    if detect_nvidia():
        return "nvidia"
    if detect_amd():
        return "amd"
    if detect_intel():
        return "intel"
    return "cpu"


def main() -> int:
    base = Path(os.environ.get("BASE_PATH", ".")).resolve()
    repo_root = Path(__file__).resolve().parent.parent
    if base == Path(".").resolve():
        base = repo_root

    mode = detect()
    print(f"Detected compute: {mode}")

    # Compose override content per mode
    overrides = {
        "nvidia": {
            "ollama": {
                "deploy": {
                    "resources": {
                        "reservations": {
                            "devices": [
                                {"driver": "nvidia", "count": "all", "capabilities": ["gpu"]}
                            ]
                        }
                    }
                }
            },
            "comfyui": {
                "image": "yanwk/comfyui-boot:cu128-slim",
                "environment": {
                    "CLI_ARGS": "--disable-xformers --lowvram",
                    "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True,pinned_use_cuda_host_register:True",
                },
                "deploy": {
                    "resources": {
                        "reservations": {
                            "devices": [
                                {"driver": "nvidia", "count": "all", "capabilities": ["gpu"]}
                            ]
                        }
                    }
                },
            },
        },
        "amd": {
            "ollama": {
                "image": "ollama/ollama:rocm",
                "devices": ["/dev/kfd", "/dev/dri"],
                "security_opt": ["seccomp:unconfined"],
            },
            "comfyui": {
                "image": "yanwk/comfyui-boot:rocm",
                "environment": {"CLI_ARGS": "--disable-xformers --lowvram"},
                "devices": ["/dev/kfd", "/dev/dri"],
                "security_opt": ["seccomp:unconfined"],
            },
        },
        "intel": {
            "ollama": {},  # CPU; Intel XPU not in standard Ollama image
            "comfyui": {
                "image": "yanwk/comfyui-boot:xpu",
                "environment": {"CLI_ARGS": "--disable-xformers --lowvram"},
                "devices": ["/dev/dri"],
            },
        },
        "cpu": {
            "ollama": {},
            "comfyui": {
                "image": "yanwk/comfyui-boot:cpu",
                "environment": {"CLI_ARGS": "--cpu"},
            },
        },
    }

    def format_override(cfg: dict) -> str:
        lines = ["# Auto-generated by scripts/detect_hardware.py", "services:"]
        for svc, opts in cfg.items():
            if not opts:
                continue
            lines.append(f"  {svc}:")
            for k, v in opts.items():
                if v is None:
                    continue
                if k == "image":
                    lines.append(f"    image: {v}")
                elif k == "environment":
                    lines.append("    environment:")
                    for ek, ev in v.items():
                        lines.append(f"      - {ek}={ev}")
                elif k == "deploy":
                    lines.append("    deploy:")
                    lines.append("      resources:")
                    lines.append("        reservations:")
                    lines.append("          devices:")
                    for d in v["resources"]["reservations"]["devices"]:
                        lines.append("            - driver: " + d["driver"])
                        lines.append("              count: " + str(d["count"]))
                        lines.append("              capabilities: " + str(d["capabilities"]))
                elif k == "devices":
                    lines.append("    devices:")
                    for d in v:
                        lines.append(f"      - {d}")
                elif k == "security_opt":
                    lines.append("    security_opt:")
                    for s in v:
                        lines.append(f"      - {s}")
        return "\n".join(lines)

    cfg = overrides[mode]
    override_content = format_override(cfg)
    override_path = base / "docker-compose.compute.yml"

    override_path.write_text(override_content, encoding="utf-8")
    print(f"Wrote {override_path}")

    # Append COMPOSE_FILE to .env so docker compose up uses the compute override
    # Windows uses ; as path separator, Linux/Mac use :
    sep = ";" if platform.system() == "Windows" else ":"
    env_path = base / ".env"
    compute_vars = f"""
# Auto-generated by scripts/detect_hardware.py
COMPUTE_MODE={mode}
COMPOSE_FILE=docker-compose.yml{sep}docker-compose.compute.yml
"""
    if env_path.exists():
        content = env_path.read_text(encoding="utf-8")
        new_compose_file = f"COMPOSE_FILE=docker-compose.yml{sep}docker-compose.compute.yml"
        if re.search(r"COMPOSE_FILE=", content):
            content = re.sub(r"COMPOSE_FILE=.*", new_compose_file, content)
        else:
            content = content.rstrip() + "\n" + new_compose_file + "\n"
        if re.search(r"COMPUTE_MODE=", content):
            content = re.sub(r"COMPUTE_MODE=.*", f"COMPUTE_MODE={mode}", content)
        else:
            content = content.rstrip() + f"\nCOMPUTE_MODE={mode}\n"
        env_path.write_text(content, encoding="utf-8")
        print(f"Updated {env_path} (COMPOSE_FILE, COMPUTE_MODE)")
    else:
        env_compute = base / ".env.compute"
        env_compute.write_text(f"# Auto-generated\nCOMPUTE_MODE={mode}\nCOMPOSE_FILE=docker-compose.yml{sep}docker-compose.compute.yml\n", encoding="utf-8")
        print(f"Wrote {env_compute} (create .env from .env.example, then re-run detect)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
